services:
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:7.2.3-alpine
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        networks:
            project_net:
                ipv4_address: ${REDIS_HOST}

    pg:
        container_name: ${PROJECT_NAME}_pg
        image: postgres:17.5-bookworm
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        shm_size: ${POSTGRES_SHM_SIZE}mb
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ../Database/data:/var/lib/postgresql/data
        networks:
            project_net:
                ipv4_address: ${POSTGRES_HOST}

networks:
    project_net:
        name: ${PROJECT_NAME}_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_NETWORK}
