#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_PROD="$SCRIPT_DIR/.env.prod"

# Check jq
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required. Install with: sudo apt install -y jq"
    exit 1
fi

# Check .env.prod exists
if [ ! -f "$ENV_PROD" ]; then
    echo "Error: .env.prod not found at $ENV_PROD"
    echo "Please create it from the template in DEPLOYMENT.md"
    exit 1
fi

# Lookup a key in .env.prod; fall back to default if not found or empty
get_value() {
    local key="$1"
    local default="$2"
    local value
    value=$(grep "^${key}=" "$ENV_PROD" | cut -d'=' -f2-)
    if [ -z "$value" ]; then
        echo "$default"
    else
        echo "$value"
    fi
}

# Process each service directory that contains a key.json
for key_json in "$SCRIPT_DIR"/*/key.json; do
    service_dir="$(dirname "$key_json")"
    service_name="$(basename "$service_dir")"
    output_env="$service_dir/.env"

    echo "Generating ${service_name}/.env ..."

    {
        echo "# Auto-generated by env-generator.sh — do not edit manually"
        echo "PROJECT_NAME=$(get_value PROJECT_NAME yanduoerp)"
        echo ""

        # Iterate through each group in key.json
        for group in $(jq -r 'keys[]' "$key_json"); do
            echo "# ${group}"
            for key in $(jq -r ".[\"${group}\"] | keys[]" "$key_json"); do
                default=$(jq -r ".[\"${group}\"][\"${key}\"]" "$key_json")
                value=$(get_value "$key" "$default")
                echo "${key}=${value}"
            done
            echo ""
        done
    } > "$output_env"

    echo "  -> ${output_env}"
done

# 產生 docker-compose-app.yaml 使用的頂層 .env（包含 port 變數）
{
    echo "# Auto-generated by env-generator.sh — do not edit manually"
    for key in PROJECT_NAME BACKEND_PORT FRONTEND_PORT; do
        echo "${key}=$(get_value "$key" "")"
    done
} > "$SCRIPT_DIR/.env"
echo "Generating .env (for docker-compose-app.yaml) ..."
echo "  -> $SCRIPT_DIR/.env"

echo ""
echo "Done. All .env files generated from .env.prod"
