FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY SpringBoot/pom.xml .
RUN mvn dependency:go-offline -q
COPY SpringBoot/src ./src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/target/app.jar .
ENTRYPOINT ["java", "-jar", "app.jar"]
